'use strict';
const E=ForestEngine,$=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const art={},sprites={},keys={left:false,right:false},fx=[];let state=E.fresh(),mode='intro',beforeHelp='intro',camera=0,clock=0,last=0,jump=false,release=false,toastTimer=0,soundOn=false,audioCtx=null,uiStamp='',wonShown=false;
const names={idle:'image13.png',run:'image21.png',jump:'image22.png',fall:'image4.png',land:'image23.png',enemy:'image18.png',tiles:'image9.png',props:'image11.png',items:'image14.png',hearts:'image16.png',far:'image12.png',mid:'image20.png',front:'image24.png'};
function surface(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
// The reference sheets have a baked-in checkerboard. Key only neutral background
// pixels connected to the outside of each crop; enclosed highlights are preserved.
function sprite(img,rect){const r=rect||[0,0,img.width,img.height],c=surface(r[2],r[3]),g=c.getContext('2d');g.drawImage(img,...r,0,0,c.width,c.height);const im=g.getImageData(0,0,c.width,c.height),d=im.data,n=c.width*c.height,seen=new Uint8Array(n),queue=new Int32Array(n);let head=0,tail=0;
 function add(i){if(i<0||i>=n||seen[i])return;seen[i]=1;const p=i*4,a=d[p],b=d[p+1],c=d[p+2];if(d[p+3]===0||(Math.min(a,b,c)>157&&Math.max(a,b,c)-Math.min(a,b,c)<35)){queue[tail++]=i;d[p+3]=0;}}
 for(let x=0;x<c.width;x++){add(x);add((c.height-1)*c.width+x);}for(let y=0;y<c.height;y++){add(y*c.width);add(y*c.width+c.width-1);}while(head<tail){const i=queue[head++],x=i%c.width;if(x)add(i-1);if(x<c.width-1)add(i+1);add(i-c.width);add(i+c.width);}
 g.putImageData(im,0,0);let x0=c.width,y0=c.height,x1=0,y1=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(d[(y*c.width+x)*4+3]>100){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}
 if(x1<x0)return c;const out=surface(x1-x0+1,y1-y0+1);out.getContext('2d').drawImage(c,x0,y0,out.width,out.height,0,0,out.width,out.height);return out;
}
function load(){return Promise.all(Object.entries(names).map(([key,file])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{art[key]=im;resolve();};im.onerror=()=>reject(new Error('Could not load '+file));im.src=window.EMBEDDED_ASSETS?.[file]||'assets/'+file;}))).then(()=>{
 for(const k of ['idle','run','jump','fall','land','enemy'])sprites[k]=sprite(art[k]);
 for(const [key,start,end] of [['mid',.18,.88],['front',.77,1]]){const layer=surface(1210,685),g=layer.getContext('2d');g.drawImage(art[key],0,0,1210,685);g.globalCompositeOperation='destination-in';const fade=g.createLinearGradient(0,0,0,685);fade.addColorStop(0,'transparent');fade.addColorStop(start,'transparent');fade.addColorStop(end,'black');g.fillStyle=fade;g.fillRect(0,0,1210,685);art[key+'Layer']=layer;}
 sprites.coin=sprite(art.items,[20,170,300,390]);sprites.gem=sprite(art.items,[332,170,288,395]);sprites.heart=sprite(art.hearts,[38,118,286,190]);sprites.empty=sprite(art.hearts,[912,118,300,190]);
 sprites.tile=sprite(art.tiles,[130,30,107,95]);sprites.dirt=sprite(art.tiles,[135,141,98,80]);sprites.stone=sprite(art.tiles,[134,249,103,93]);sprites.platform=sprite(art.tiles,[714,19,130,133]);sprites.ruin=sprite(art.tiles,[1090,551,180,149]);
 sprites.bush=sprite(art.props,[5,512,270,191]);sprites.fern=sprite(art.props,[278,518,230,182]);sprites.flowers=sprite(art.props,[484,300,216,207]);sprites.mushroom=sprite(art.props,[1035,24,241,236]);sprites.log=sprite(art.props,[758,539,263,155]);sprites.lantern=sprite(art.props,[1027,273,245,235]);
 $('coin-icon').src=sprites.coin.toDataURL();$('total').textContent=state.total;$('start').disabled=false;$('start-label').textContent='Begin your journey';requestAnimationFrame(frame);
 }).catch(err=>{$('start-label').textContent='Artwork could not load';$('intro').querySelector('p').textContent='Keep the assets folder beside index.html, or open the standalone Play Moonlit Hollow.html file.';console.error(err);});}
function drawSprite(s,x,y,w,h,flip=false,alpha=1){if(!s)return;ctx.save();ctx.globalAlpha*=alpha;ctx.translate(Math.round(x+(flip?w:0)),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(s,0,0,w,h);ctx.restore();}
function fitted(s,x,y,h,flip=false){drawSprite(s,x,y,s.width/s.height*h,h,flip);}
function glow(x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function background(cam,title=false){ctx.imageSmoothingEnabled=true;if(title){ctx.drawImage(art.front,0,0,960,543);}else{
 const w=1210;for(const [key,speed,opacity] of [['far',.045,1],['midLayer',.18,.96]]){ctx.save();ctx.globalAlpha=opacity;const off=-(cam*speed)%w;for(let i=-1;i<2;i++){ctx.save();ctx.translate(off+i*w,0);if(i%2){ctx.translate(w,0);ctx.scale(-1,1);}ctx.drawImage(art[key],0,-65,w,685);ctx.restore();}ctx.restore();}
 ctx.fillStyle='#07202727';ctx.fillRect(0,0,960,540);
 }ctx.imageSmoothingEnabled=false;
 // Near silhouettes form a separate foreground plane with a faster camera rate.
 if(!title){ctx.save();ctx.globalAlpha=.44;for(let i=0;i<7;i++){let x=((i*283-cam*.52)%1500+1500)%1500-200;ctx.fillStyle='#081e21';ctx.fillRect(x,-10,9+i%3*6,400);ctx.fillRect(x-7,10,8,140);ctx.fillRect(x+8,25,5,230);}ctx.restore();}
 const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#03101644');g.addColorStop(.5,'transparent');g.addColorStop(1,'#04141666');ctx.fillStyle=g;ctx.fillRect(0,0,960,540);
 for(let i=0;i<35;i++){const x=((i*93.7+Math.sin(clock*.25+i)*20-cam*.27)%1040+1040)%1040-40,y=110+(i*67%350)+Math.sin(clock*.55+i*2)*13,a=.25+(Math.sin(clock*1.4+i)+1)*.23;ctx.fillStyle=`rgba(222,225,137,${a})`;ctx.fillRect(x,y,i%3===0?3:2,2);if(i%5===0)glow(x,y,13,'#b9df6625');}
}
function terrain(cam){for(const q of E.platforms){const x=q.x-cam;if(x>1000||x+q.w<-60)continue;if(q.ground){ctx.save();ctx.beginPath();ctx.rect(x,q.y,q.w,540-q.y);ctx.clip();for(let a=0;a<q.w;a+=48){drawSprite(sprites.tile,x+a,q.y,49,48);for(let y=q.y+48;y<550;y+=43)drawSprite(sprites.dirt,x+a,y,49,44);}ctx.fillStyle='#08161b80';ctx.fillRect(x,q.y+73,q.w,140);ctx.restore();}else{
 drawSprite(sprites.platform,x,q.y-3,q.w,Math.min(76,q.w*.55));
 }
 }
 E.ground.forEach(([x,w,y],i)=>{const sx=x-cam;if(sx>1100||sx+w<-200)return;const props=['fern','flowers','bush','mushroom','log'];for(let j=0;j<Math.floor(w/210);j++){const name=props[(i+j)%props.length],h=name==='mushroom'?62:41;fitted(sprites[name],sx+65+j*205,y-h+4,h,j%2===0);}if(i===0||i===5||i===12)fitted(sprites.ruin,sx+w-140,y-108,113);});
}
function portal(x,y){glow(x,y-74,108,'#dce6a22a');ctx.save();ctx.strokeStyle='#d3d994';ctx.lineWidth=3;ctx.shadowColor='#ccec87';ctx.shadowBlur=16;ctx.beginPath();ctx.ellipse(x,y-56,31,53,0,0,Math.PI*2);ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#f4e6b399';ctx.beginPath();ctx.ellipse(x,y-56,24,46,0,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#e8e7aa';for(let i=0;i<7;i++){const a=clock*.4+i;ctx.fillRect(x+Math.cos(a)*23,y-56+Math.sin(a)*42,2,2);}ctx.restore();}
function checkpoint(){const x=4220-camera,y=455;fitted(sprites.lantern,x-15,y-115,113);if(state.checkpoint)glow(x+27,y-52,70,'#edca6344');if(Math.abs(state.player.x-4220)<230){ctx.fillStyle='#e7d7aa';ctx.font='9px Arial';ctx.textAlign='center';ctx.fillText(state.checkpoint?'JOURNEY SAVED':'LANTERN SANCTUARY',x+35,y-127);}}
function particle(x,y,color,n=10){for(let i=0;i<n;i++)fx.push({x,y,vx:Math.cos(i/n*Math.PI*2)*60,vy:Math.sin(i/n*Math.PI*2)*65-20,life:.7,color});}
function foreground(cam){ctx.save();ctx.imageSmoothingEnabled=true;ctx.globalAlpha=.75;for(let i=-1;i<2;i++)ctx.drawImage(art.frontLayer,-(cam*.65)%1210+i*1210,-90,1210,685);ctx.imageSmoothingEnabled=false;for(let i=0;i<9;i++){const x=((i*231-cam*.8)%1750+1750)%1750-220;fitted(sprites[i%2?'fern':'bush'],x,498,75,i%2===0);}ctx.restore();const g=ctx.createLinearGradient(0,485,0,540);g.addColorStop(0,'transparent');g.addColorStop(1,'#03140ede');ctx.fillStyle=g;ctx.fillRect(0,485,960,55);}
function render(dt){ctx.clearRect(0,0,960,540);const title=mode==='intro'||(mode==='help'&&beforeHelp==='intro');if(title){background(0,true);glow(711,377,115,'#e4d16b19');drawSprite(sprites.platform,626,442,197,111);fitted(sprites.idle,687,341+Math.sin(clock*1.8)*1.5,106);foreground(0);return;}
 camera+=(Math.max(0,Math.min(E.W-960,state.player.x-310))-camera)*Math.min(1,dt*7);background(camera);terrain(camera);checkpoint();portal(10615-camera,450);
 for(const c of state.coins){if(c.got)continue;const x=c.x-camera,y=c.y+Math.sin(clock*2.6+c.x)*4;if(x<-30||x>990)continue;const h=c.kind==='heart'?25:c.kind==='gem'?31:21;glow(x,y,c.kind==='gem'?35:24,c.kind==='gem'?'#55dcff22':c.kind==='heart'?'#ff829b22':'#ffe78420');fitted(sprites[c.kind],x-h/2,y-h/2,h);}
 for(const e of state.enemies){if(!e.alive||e.x-camera<-90||e.x-camera>1050)continue;fitted(sprites.enemy,e.x-camera-8,e.y-15+Math.sin(clock*7)*1.5,49,e.dir<0);}
 const p=state.player;let pose=p.onGround?(Math.abs(p.vx)>0?'run':'idle'):(p.vy<0?'jump':'fall');const bob=p.onGround&&p.vx?Math.sin(clock*18)*2:0;ctx.save();if(p.inv>0&&Math.floor(clock*12)%2)ctx.globalAlpha=.35;const s=sprites[pose],h=pose==='fall'?54:64,w=h*s.width/s.height;drawSprite(s,p.x-camera+p.w/2-w/2,p.y+p.h-h+3+bob,w,h,p.face<0);ctx.restore();glow(p.x-camera+30*p.face,p.y+10,30,'#f0d86811');
 for(let i=fx.length-1;i>=0;i--){const f=fx[i];if(mode==='play'){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=95*dt;}ctx.globalAlpha=Math.max(0,f.life/.7);ctx.fillStyle=f.color;ctx.fillRect(f.x-camera,f.y,3,3);ctx.globalAlpha=1;if(f.life<=0)fx.splice(i,1);}foreground(camera);
}
function ui(){const p=state.player,stamp=p.hp+':'+state.score;if(uiStamp!==stamp){uiStamp=stamp;$('score').textContent=String(state.score).padStart(2,'0');$('health').replaceChildren(...Array.from({length:3},(_,i)=>{const im=new Image();im.src=(i<p.hp?sprites.heart:sprites.empty).toDataURL();im.alt=i<p.hp?'Full heart':'Empty heart';return im;}));$('health').setAttribute('aria-label',p.hp+' of 3 hearts');}$('progress').style.width=(p.x/E.W*100)+'%';$('region').textContent=p.x<3400?'THE WHISPERING WOODS':p.x<7200?'RUINS OF THE MOON':'THE LAST LANTERN';}
function frame(t){const dt=Math.min((t-last)/1000||.016,.05);last=t;clock+=dt;if(mode==='play'){let left=dt;let first=true;while(left>0){const h=Math.min(left,1/120);E.step(state,{...keys,jump:first&&jump,release:first&&release},h);first=false;left-=h;for(const e of state.events)event(e);if(state.dead||state.won)break;}jump=release=false;if(state.dead)end(false);else if(state.won)end(true);ui();}render(dt);requestAnimationFrame(frame);}
function event(e){const p=state.player;if(e==='coin'||e==='gem'||e==='heart'){particle(p.x+10,p.y+15,e==='gem'?'#6bedfa':e==='heart'?'#ffa4b6':'#f1d46f',12);tone(e==='gem'?1100:e==='heart'?660:880,.12);if(e==='heart')toast('A little forest magic. One heart restored.');}if(e==='jump')tone(260,.08,'sine',420);if(e==='hurt'){tone(150,.2,'triangle',60);toast(p.hp>0?'Keep going. The forest believes in you.':'');}if(e==='checkpoint'){tone(440,.5,'sine',880);toast('Lantern lit · Progress saved · Hearts restored');}if(e==='stomp'){tone(350,.12,'triangle',650);particle(p.x,p.y+40,'#95cba5');}if(e==='win')tone(660,.7,'sine',1320);}
function tone(freq,dur,type='sine',to=freq){if(!soundOn)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(to,audioCtx.currentTime+dur);g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch(e){soundOn=false;}}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').classList.toggle('show',!!text);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600);}
function clearInput(){keys.left=keys.right=jump=release=false;}
function start(){state=E.fresh();camera=0;fx.length=0;uiStamp='';wonShown=false;mode='play';clearInput();$('intro').hidden=true;$('modal').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');canvas.focus();ui();toast('Follow the starlight → Hold your jump to go higher.');}
function showModal(eyebrow,title,copy,button,help=false){$('modal-eyebrow').textContent=eyebrow;$('modal-title').textContent=title;$('modal-copy').textContent=copy;$('resume').innerHTML=button+' <span>→</span>';$('instructions').hidden=!help;$('modal').hidden=false;document.body.classList.remove('playing');clearInput();$('resume').focus();}
function pause(){if(mode!=='play')return;mode='pause';showModal('TAKE A BREATH','The forest can wait.','Your adventure is right where you left it.','Back to the woods');}
function resume(){if(mode==='dead'||mode==='won'){start();return;}if(mode==='help'&&beforeHelp==='intro'){mode='intro';$('modal').hidden=true;$('start').focus();return;}mode='play';$('modal').hidden=true;document.body.classList.add('playing');clearInput();canvas.focus();}
function end(win){if(wonShown)return;wonShown=true;mode=win?'won':'dead';const m=Math.floor(state.elapsed/60),s=String(Math.floor(state.elapsed%60)).padStart(2,'0');showModal(win?'THE FOREST REMEMBERS YOU':'EVERY PATH HAS A SECOND CHANCE',win?'You brought the light home.':'Rest, little wanderer.',win?`${state.score} of ${state.total} starlights gathered · ${state.gems} moon crystals · ${m}:${s}. There is always more to discover.`:'The woods are patient. Begin again, or return to your lantern with three full hearts.',win?'Wander again':'Return to the lantern');}
const jumpCodes=['Space','ArrowUp','KeyW'];document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target instanceof HTMLButtonElement)return;if(['ArrowLeft','ArrowRight',...jumpCodes,'Escape','KeyP'].includes(e.code))e.preventDefault();if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(mode==='play')pause();else if(mode==='pause'||mode==='help')resume();return;}if(mode!=='play')return;if(e.code==='ArrowLeft'||e.code==='KeyA')keys.left=true;if(e.code==='ArrowRight'||e.code==='KeyD')keys.right=true;if(jumpCodes.includes(e.code)&&!e.repeat)jump=true;});document.addEventListener('keyup',e=>{if(e.code==='ArrowLeft'||e.code==='KeyA')keys.left=false;if(e.code==='ArrowRight'||e.code==='KeyD')keys.right=false;if(jumpCodes.includes(e.code))release=true;});
$('start').onclick=start;$('pause').onclick=pause;$('restart').onclick=start;$('resume').onclick=()=>{if(mode==='dead'){state.dead=false;state.player.hp=3;state.player.x=state.checkpoint?4220:90;state.player.y=350;state.player.vx=state.player.vy=0;state.player.inv=1.5;state.player.onGround=false;state.player.coyote=state.player.buffer=0;wonShown=false;mode='pause';}resume();};
$('help').onclick=()=>{if(mode==='help'){resume();return;}beforeHelp=mode;if(mode==='dead'||mode==='won')return;mode='help';showModal('A FEW THINGS FOR THE TRAIL','Follow your curiosity.','Reach the ancient gate at the far end of the forest. Collectibles reward exploration; none are required to finish.','Got it. Let’s wander.',true);};
$('sound').onclick=()=>{soundOn=!soundOn;$('sound-slash').hidden=soundOn;$('sound').setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on');tone(600,.1);};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.game-frame').requestFullscreen();}catch(e){toast('Full screen is unavailable in this browser.');}};
window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(mode!=='play')return;const k=b.dataset.key;if(k==='jump')jump=true;else keys[k]=true;});const up=()=>{const k=b.dataset.key;if(k==='jump')release=true;else keys[k]=false;};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);});
load();
